{{ if eq .chezmoi.os "darwin" -}}
[".config/iterm/dracula"]
    type = "git-repo"
    url = "https://github.com/dracula/iterm.git"
    refreshPeriod = "168h"
{{- end }}

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/dracula"]
    type = "git-repo"
    url = "https://github.com/dracula/zsh"
    refreshPeriod = "168h"

[".local/bin/ansi"]
    type = "file"
    url = "https://raw.githubusercontent.com/fidian/ansi/master/ansi"
    refreshPeriod = "168h"

[".local/share/fasd"]
    type = "archive"
    url = "https://github.com/clvv/fasd/archive/refs/tags/1.0.1.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/zsh/funcs/_git"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh"
    refreshPeriod = "168h"

[".local/share/fzf"]
    type = "git-repo"
    url = "https://github.com/junegunn/fzf.git"
    refreshPeriod = "168h"

[".config/zsh/funcs/_fzf"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh"
    refreshPeriod = "168h"

[".config/zsh/funcs/_just"]
    type = "file"
    url = "https://raw.githubusercontent.com/casey/just/master/completions/just.zsh"
    refreshPeriod = "168h"

[".config/zsh/funcs/_golang"]
    type = "file"
    url = "https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_golang"
    refreshPeriod = "168h"
