{{ if eq .chezmoi.os "darwin" -}}
[".config/iterm/dracula"]
    type = "git-repo"
    url = "https://github.com/dracula/iterm.git"
    refreshPeriod = "168h"
{{- end }}

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/dracula"]
    type = "git-repo"
    url = "https://github.com/dracula/zsh"
    refreshPeriod = "168h"

# [".local/share/zsh/autocomplete"]
#     type = "git-repo"
#     url = "https://github.com/marlonrichert/zsh-autocomplete.git"
#     refreshPeriod = "168h"

[".local/bin/ansi"]
    type = "file"
    url = "https://raw.githubusercontent.com/fidian/ansi/master/ansi"
    refreshPeriod = "168h"

[".local/share/fasd"]
    type = "archive"
    url = "https://github.com/clvv/fasd/archive/refs/tags/1.0.1.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".local/share/fzf"]
    type = "git-repo"
    url = "https://github.com/junegunn/fzf.git"
    refreshPeriod = "168h"

# [".local/share/zsh/zsh-z"]
#     type = "git-repo"
#     url = "https://github.com/agkozak/zsh-z.git"
#     refreshPeriod = "168h"

[".profile.d/40_completion_git.bash"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    refreshPeriod = "168h"

[".config/zsh/funcs/_git"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh"
    refreshPeriod = "168h"

# [".profile.d/41_completion_fzf.zsh"]
#     type = "file"
#     url = "https://raw.githubusercontent.com/lincheney/fzf-tab-completion/master/zsh/fzf-zsh-completion.sh"
#     refreshPeriod = "168h"

[".profile.d/40_completion_cargo.bash"]
    type = "file"
    url = "https://raw.githubusercontent.com/rust-lang/cargo/0.70.1/src/etc/cargo.bashcomp.sh"
    refreshPeriod = "168h"
