[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "24h"

[".config/tmux/plugins/tmux-resurrect"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-resurrect"
    refreshPeriod = "24h"

[".config/tmux/plugins/dracula"]
    type = "git-repo"
    url = "https://github.com/dracula/tmux"
    refreshPeriod = "24h"

[".config/iterm/dracula"]
    type = "git-repo"
    url = "https://github.com/dracula/iterm.git"
    refreshPeriod = "24h"

[".config/nvim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "24h"

{{ $fzfVersion := "0.17.5" -}}

[".profile.d/40_completion_fzf"]
    type = "file"
    url = "https://github.com/junegunn/fzf/raw/{{ $fzfVersion }}/shell/completion.bash"
    refreshPeriod = "24h"

[".profile.d/40_completion_fzf_keys"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/fzf/{{ $fzfVersion }}/shell/key-bindings.bash"
    refreshPeriod = "24h"
