---
cache:
  global: 2

go:
  version: "1.20.1"
golangci_lint:
  version: "v1.51.2"
bazelisk:
  version: "v1.16.0"
helix:
  version: "22.12"
tmux:
  version: "3.3a"

manifest:
  go:
    version: "1.20.1"
