[".config/iterm/dracula"]
    type = "git-repo"
    url = "https://github.com/dracula/iterm.git"
    refreshPeriod = "168h"

[".profile.d/40_completion_git"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    refreshPeriod = "168h"

[".profile.d/40_completion_cargo"]
    type = "file"
    url = "https://raw.githubusercontent.com/rust-lang/cargo/66789e531a1b75368fd7ca39ce2360b58cf2c709/src/etc/cargo.bashcomp.sh"
    refreshPeriod = "168h"
