#!/usr/bin/env bash

shopt -s autocd 2>/dev/null
shopt -s cdspell 2>/dev/null
shopt -s globstar 2>/dev/null
shopt -s nocaseglob 2>/dev/null

# Well-known paths
export PATH="$HOME/.local/bin:$HOME/bin:/usr/local/sbin:/usr/local/bin:$PATH"
_profiled_files="$(find "$HOME/.profile.d" -type f | sort)"

function PATH_add() {
    for dir in "$@"; do
        [ -z "$dir" ] || PATH="$dir${PATH:+:${PATH}}"
    done

    # https://stackoverflow.com/a/44232192
    PATH="$(perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, $ENV{PATH}))')"

    export PATH
}

for f in $_profiled_files; do
    source "$f" || echo "[$HOME/.dotrc] Failed to source $f"
done

if command -v direnv >/dev/null; then
    eval "$(direnv hook bash)"
fi

set +e
