#!/usr/bin/env just --justfile

@default:
    just --justfile {{ justfile() }} --list | grep -v default

alias update := chezmoi
chezmoi:
    chezmoi update --init

alias cb := change-branch
change-branch PATTERN="":
    #!/usr/bin/env bash
    branch="$(git branch | grep '{{ PATTERN }}' | grep -v '^\+' | awk '{print $NF}' | fzf)"
    [ -z "$branch" ] || git checkout "$branch"

alias ec := edit-changed
edit-changed PATTERN="":
    #!/usr/bin/env bash
    changed="$(git changed | grep '{{ PATTERN }}' | fzf)"
    [ -z "$changed" ] || "$EDITOR" "$changed"
