theme = "dracula2"

[editor]
shell = ["/bin/bash", "-c"]
gutters = ["diagnostics", "line-numbers", "spacer"]
mouse = true
auto-completion = true
auto-format = true
auto-info = true
rulers = [80, 100, 120]
auto-pairs = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
# mode.normal = "NORMAL"
# mode.insert = "INSERT"
# mode.select = "VISUAL"

[keys.normal]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"+" = ":pipe goimports"
V = ["select_mode", "extend_to_line_bounds"]
D = ["extend_to_line_end", "delete_selection"]
d = { d = ["extend_to_line_bounds", "delete_selection"], t = ["extend_till_char"], s = ["surround_delete"], i = ["select_textobject_inner"], a = ["select_textobject_around"] }
x = "delete_selection"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection"]
w = ["move_next_word_start", "move_char_right", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
"C-c" = ["collapse_selection", "normal_mode"]
"C-r" = ["redo"]
"C-/" = ["toggle_comments"]

[keys.insert]
";" = { ";" = "normal_mode" }
esc = ["collapse_selection", "normal_mode"]
"C-c" = ["collapse_selection", "normal_mode"]
"C-/" = ["toggle_comments"]

[keys.select]
d = ["yank_main_selection_to_clipboard", "delete_selection"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
p = "replace_selections_with_clipboard" # No life without this
P = "paste_clipboard_before"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"C-c" = ["collapse_selection", "normal_mode"]
"C-/" = ["toggle_comments"]
