theme = "dracula2"

[editor]
shell = ["/bin/bash", "-c"]
gutters = ["diagnostics", "line-numbers", "spacer"]
mouse = true
auto-completion = true
auto-format = true
auto-info = true
rulers = [80, 100, 120]
auto-pairs = true
true-color = true
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true

[editor.file-picker]
hidden = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "spacer",  "spacer", "position", "position-percentage", "spacer", "spacer", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[keys.normal]
D = ["extend_to_line_end", "delete_selection"]
w = ["move_next_word_start", "move_char_right", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"C-c" = ["toggle_comments"]
"C-r" = ["redo"]
"C-/" = ["toggle_comments"]
";" = ["repeat_last_motion"]
space = { "." = [":fmt"]}

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
"C-c" = ["toggle_comments"]
"C-/" = ["toggle_comments"]

[keys.select]
d = ["yank_main_selection_to_clipboard", "delete_selection"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"C-c" = ["toggle_comments"]
"C-/" = ["toggle_comments"]
