[language-server.clangd]
command = "clangd"
args = ["--clang-tidy", "--header-insertion=iwyu"] 


[language-server.clangd.config]
Completion.AllScopes = "Yes"
Diagnostics.UnusedIncludes = "Strict"
Index.StandardLibrary = "Yes"

[[language]]
name = "go"
language-servers = ["gopls"]

[language-server.gopls.config]
gofumpt = true
memoryMode = "DegradeClosed"
deepCompletion = true
staticcheck = true

[language-server.gopls.config.formatting]
gofumpt = true

[language-server.gopls.config.analyses]
fieldalignment = true
nilness = true
shadow = true
unusedparams = true
unreachable = true

[[language]]
name = "yaml"

[language-server.yaml-language-server.config]
yaml.keyOrdering = false

[[language]]
name = "rust"

[[language]]
name = "cpp"
auto-format = true

[language.formatter]
command = "clang-format"
args = [
  "--sort-includes",
  "--Werror",
]

[[language]]
name = "starlark"
file-types = ["starlark", "BUILD", { suffix = ".star" }, { suffix = ".bazel"}, { suffix = ".bzl" }, { suffix = ".build" }]
