[language-server.gopls.config]
gofumpt = true
deepCompletion = true
staticcheck = true

[language-server.gopls.config.analyses]
nilness = true
shadow = true
unusedparams = true
unreachable = true

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format", args = ["--Werror"] }

[language-server.clangd]
command = "clangd"
args = ["--clang-tidy", "--completion-style=detailed", "--header-insertion=iwyu"] 

[language-server.clangd.config]
Completion.AllScopes = "Yes"
Diagnostics.UnusedIncludes = "Strict"
Index.StandardLibrary = "Yes"

[[language]]
name = "rust"
formatter = { command = "rustfmt" }

[[language]]
name = "python"
formatter = { command = "sh", args = ["-c", "black --quiet --line-length=79 - | isort -"] }
auto-format = true

[language-server.pylsp.config.pylsp]
plugins.black.enabled = true
plugins.flake8.enabled = true
plugins.pylint.enabled = true
plugins.pyflakes.enabled = false
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = false
plugins.isort.enabled = true
plugins.rope_autoimport.enabled = true

[[language]]
name = "bash"
indent = { tab-width = 2, unit = "  " }
formatter = { command = 'shfmt', args = ["-i", "2"] }
auto-format = true

[language-server.yaml-language-server.config]
yaml.keyOrdering = false
