[language-server.clangd]
command = "clangd"
args = ["--clang-tidy", "--header-insertion=iwyu"] 

[language-server.clangd.config.Completion]
AllScopes = "Yes"

[language-server.clangd.config.Index]
StandardLibrary = "Yes"

[language-server.clangd.config.Diagnostics]
UnusedIncludes = "Strict"

[[language]]
name = "go"

[language.config]
gofumpt = true
memoryMode = "DegradeClosed"
deepCompletion = true
staticcheck = true

[language.config.analyses]
fieldalignment = true
nilness = true
shadow = true
unusedparams = true
unreachable = true

[[grammar]]
name = "go"
source = { git = "https://github.com/tree-sitter/tree-sitter-go", rev = "64457ea6b73ef5422ed1687178d4545c3e91334a" }

[[language]]
name = "yaml"

[language.config]
yaml.keyOrdering = false

[[language]]
name = "rust"

[[language]]
name = "cpp"
auto-format = true

[language.formatter]
command = "clang-format"
args = [
  "--Werror",
]

[language.config]
Completion.AllScopes = "Yes"
Diagnostics.UnusedIncludes = "Strict"

[[language]]
name = "starlark"
file-types = ["starlark", { suffix = ".star" }, { suffix = ".bazel"}]
