---
- name: .ssh/authorized_keys
  copy:
    src: home/.ssh/authorized_keys
    dest: ~/.ssh/
    mode: u=rw,g=r,o=r
  when: "'personal' in group_names"
  tags:
    - devenv
    - config
    - personal
    - ssh

- name: .ssh/config
  blockinfile:
    path: ~/.ssh/config
    create: true
    mode: u=rw,g=r,o=r
    block: |
      Host github.com
        UpdateHostKeys yes
  tags:
    - config
    - devenv
    - personal
    - ssh

- block:
    - name: Chezmoi version check
      shell: '[[ "$(chezmoi --version 2>/dev/null)" =~ "v{{ versions.chezmoi }}" ]]'
      args:
        executable: /bin/bash
      changed_when: false
  rescue:
    - name: Chezmoi install
      shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin init git@github.com:mway/dotfiles.git
      args:
        executable: /bin/bash
  tags:
    - chezmoi
    - config

- name: Chezmoi update
  shell: chezmoi update --verbose --init --apply=false
  args:
    executable: /bin/bash
  register: chezmoi_update
  changed_when: "chezmoi_update.stdout_lines|length > 1 or chezmoi_update.stderr_lines|length > 1"
  tags:
    - chezmoi
    - config

- name: Chezmoi apply core (may lazily bootstrap tools)
  shell: |
    chezmoi apply --verbose --force \
      $HOME/.config                 \
      $HOME/.dotrc{,.bash,.zsh}     \
      $HOME/.profile.d              \
      $HOME/.local/bin              \
      $HOME/bin                     \
      && true
  args:
    executable: /bin/bash
  register: chezmoi_apply_core
  changed_when: "chezmoi_apply_core.stdout_lines|length > 1"
  tags:
    - chezmoi
    - config
