---
- name: "Pip docker"
  pip:
    executable: pip3
    name:
      - docker
      - docker-compose
    state: latest
  become: true
  when: "'personal' in group_names"
  tags:
    - dns
    - ecobee
    - grafana
    - loki
    - node-exporter
    - observability
    - services
    - victoria-metrics

- name: Node Exporter
  community.docker.docker_compose:
    project_src: "{{ local }}/etc/docker"
    services:
      - node-exporter
  become: true
  when: "'personal' in group_names"
  tags:
    - node-exporter
    - services

- name: PiHole
  community.docker.docker_compose:
    project_src: "{{ local }}/etc/docker"
    services:
      - pihole
  become: true
  when: "'personal' in group_names and 'dns' in group_names"
  tags:
    - dns
    - services
  
- name: Promtail
  community.docker.docker_compose:
    project_src: "{{ local }}/etc/docker"
    services:
      - promtail
  become: true
  when: "'personal' in group_names"
  tags:
    - services

- name: Observability
  community.docker.docker_compose:
    project_src: "{{ local }}/etc/docker"
    services:
      - grafana
      - loki
      - victoria-metrics
  become: true
  when: "'personal' in group_names and 'obs' in group_names"
  tags:
    - grafana
    - loki
    - observability
    - victoria-metrics
    - services

- name: Ecobee
  community.docker.docker_compose:
    project_src: "{{ local }}/etc/docker"
    services:
      - ecobee
  become: true
  when: "'personal' in group_names and 'probes' in group_names"
  tags:
    - ecobee
    - services
