---
- name: Tailscale - DNS
  command:
    argv:
      - tailscale
      - up
      - --accept-dns=false
      - --accept-routes
      - --advertise-exit-node=false
      - --advertise-routes=172.168.68.0/24
      - --ssh
  become: yes
  when: "'personal' in group_names and 'dns' in group_names"
  tags:
    - tailscale

- name: Tailscale - Non-DNS
  command:
    argv:
      - tailscale
      - up
      - --accept-dns
      - --accept-routes
      - --advertise-exit-node
      - --ssh
  become: yes
  when: "'personal' in group_names and 'dns' not in group_names"
  tags:
    - tailscale

- name: Node Exporter
  community.docker.docker_compose:
    project_src: "{{ local }}/etc/docker"
    services:
      - node-exporter
  become: true
  when: "'personal' in group_names"
  tags:
    - node-exporter
    - services

- name: PiHole
  community.docker.docker_compose:
    project_src: "{{ local }}/etc/docker"
    services:
      - pihole
  become: true
  when: "'dns' in group_names"
  tags:
    - dns
    - promtail
    - services
  
- name: Promtail
  community.docker.docker_compose:
    project_src: "{{ local }}/etc/docker"
    services:
      - promtail
  when: "'personal' in group_names"
  tags:
    - promtail
    - services

- name: Observability
  community.docker.docker_compose:
    project_src: "{{ local }}/etc/docker"
    services:
      - grafana
      - loki
      - victoria-metrics
  when: "'obs' in group_names"
  tags:
    - grafana
    - loki
    - obs
    - observability
    - victoria-metrics
    - services

- name: Ecobee
  community.docker.docker_compose:
    project_src: "{{ local }}/etc/docker"
    services:
      - ecobee
  become: true
  when: "'probes' in group_names"
  tags:
    - ecobee
    - services
