---
- name: mw install
  command: "mw install {{ item }}"
  register: mw_install_pkg
  changed_when: "'already installed' not in mw_install_pkg.stdout"
  tags:
    - devenv
    - tools
    - packages
  loop:
    - ag
    - bash
    - bat
    - btop
    - curl
    - difftastic
    - direnv
    - docker
    - docker-compose
    - exa
    - fd-find
    - fzf
    - git
    - jq
    - just
    - tree

- name: mw install personal
  command: "mw install {{ item }}"
  register: mw_install_personal_pkg
  changed_when: "'already installed' not in mw_install_personal_pkg.stdout"
  tags:
    - 1password
    - personal
    - tailscale
  loop:
    - 1password
    - tailscale
