---
- name: mw install
  shell: mw install {{ item }}
  args:
    executable: /bin/bash
  register: mw_install_pkgs
  changed_when: "'already installed' not in mw_install_pkgs.stdout"
  tags:
    - packages
    - tools
  loop:
    - ag
    - bash
    - bat
    - btop
    - curl
    - difftastic
    - direnv
    - docker
    - docker-compose
    - exa
    - fd-find
    - fzf
    - git
    - helix
    - jq
    - just
    - python3
    - ripgrep
    - tree
    - zellij
    - zsh

- name: mw install personal
  shell: mw install {{ item }}
  args:
    executable: /bin/bash
  register: mw_install_personal_pkgs
  changed_when: "'already installed' not in mw_install_personal_pkgs.stdout"
  tags:
    - packages
    - tools
  loop:
    - 1password
