#!/usr/bin/env bash

export BASH_SILENCE_DEPRECATION_WARNING=1
export VISUAL="nvim"
export EDITOR="$VISUAL"
export HISTCONTROL=ignoreboth:erasedups
export LS_COLORS='di=38;5;108:fi=00:*svn-commit.tmp=31:ln=38;5;116:ex=38;5;186'
export TERM="xterm-256color"
