#!/usr/bin/env bash

which go 2>&1 >/dev/null
if [ $? -eq 0 ]; then
    local _gopath="$(go env GOPATH)"
    [ -n "$_gopath" ] || _gopath="$HOME/go"

    local _gobin="$(go env GOBIN)"
    [ -n "$_gobin" ] || _gobin="$_gopath/bin"

    mkdir -p $_gopath $_gobin
    export GOPATH="$_gopath" GOBIN="$_gobin"

    PATH_add "$(go env GOROOT)/bin"
    PATH_add "$GOBIN"
fi
