#!/usr/bin/env bash

alias htop='sudo htop'
#alias ls='ls -lAG'
alias ls='exa -al'
alias mkdir='mkdir -p'
alias grep='ag'
alias rgrep='ag'
alias tmux='tmux -2'
alias vi='\nvim'
alias vim='\nvim'
alias vmore='\vim -u ~/.vimrc.more -'
alias brew-save='brew bundle dump -f ~/Brewfile'
alias just='unset _JF; [ -f justfile ] || _JF="-f $HOME/justfile"; just --unstable $_JF'
