#!/usr/bin/env bash

shopt -s globstar

export ANSIBLE_NOCOWS=1
export BASH_SILENCE_DEPRECATION_WARNING=1
export VISUAL="hx"
export EDITOR="$VISUAL"
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=100000000
export LS_COLORS='di=38;5;108:fi=00:*svn-commit.tmp=31:ln=38;5;116:ex=38;5;186'
export TERM="xterm-256color"

if command -v bat >/dev/null 2>&1; then
    export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi
