#!/usr/bin/env bash

if command -v go >/dev/null; then
    export VIM_GOPLS_MEMORY_MODE="DegradeClosed"

    [ ! -d "$HOME/go" ] || export GOPATH="$HOME/go"

    _gopath="$(go env GOPATH)"
    [ -n "$_gopath" ] || _gopath="$HOME/go"

    _gobin="$(go env GOBIN)"
    [ -n "$_gobin" ] || _gobin="$_gopath/bin"

    mkdir -p $_gopath $_gobin
    export GOPATH="$_gopath" GOBIN="$_gobin"

    PATH_add /usr/local/go/bin "$(go env GOROOT)/bin" "$GOBIN"
fi
