#!/usr/bin/env bash

alias cm='chezmoi'
alias fd='fd --no-ignore --hidden'
alias grep='rg'
alias htop='sudo htop'
alias just='unset _JF; [ -f justfile ] || _JF="-f $HOME/justfile"; just --unstable $_JF'
alias ls='exa -al'
alias mkdir='mkdir -p'
alias oplogin='eval $(op signin)'
alias tf='terraform'
alias tmux='tmux -2'
