#!/usr/bin/env bash

alias cm='chezmoi'
alias fd='fd --no-ignore --hidden'
alias htop='sudo htop'
alias ls='exa -al'
alias lsc='exa -al --color=always'
alias mkdir='mkdir -p'
alias grep='ag'
alias rgrep='ag'
alias tmux='tmux -2'
alias just='unset _JF; [ -f justfile ] || _JF="-f $HOME/justfile"; just --unstable $_JF'
alias oplogin='eval $(op signin)'
