#!/usr/bin/env bash

shopt -s autocd 2>/dev/null
shopt -s cdspell
shopt -s globstar 2>/dev/null
shopt -s nocaseglob

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
