#!/usr/bin/env bash

shopt -s autocd 2>/dev/null
shopt -s cdspell
shopt -s globstar 2>/dev/null
shopt -s nocaseglob

BASE16_SHELL="${HOME}/.config/base16-shell/base16-ocean.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL &>/dev/null
