#!/usr/bin/env bash

export SSH_AUTH_SOCK=~/.ssh/ssh-agent.sock

export GRN="\e[32m"
export HIG="\e[92m"
export YEL="\e[33m"
export HIY="\e[93m"
export RED="\[\e[31m\]"
export HIR="\e[91m"
export BLU="\[\e[34m\]"
export HIB="\e[94m"
export CYN="\[\e[36m\]"
export HIC="\e[96m"
export MAG="\e[35m"
export HIM="\e[95m"
export WHT="\e[97m"
export GRY="\[\e[90m\]"
export BLK="\e[30m"
export DEF="\e[39m"
export RESET="\[\e[0m\]"
export BOLD="\e[1m"
export DIM="\e[2m"
export BG_GRN="\e[42m"
export BG_HIG="\e[102m"
export BG_YEL="\e[43m"
export BG_HIY="\e[103m"
export BG_RED="\e[41m"
export BG_HIR="\e[101m"
export BG_BLU="\e[44m"
export BG_HIB="\e[104m"
export BG_CYN="\e[46m"
export BG_HIC="\e[106m"
export BG_MAG="\e[45m"
export BG_HIM="\e[105m"
export BG_WHT="\e[107m"
export BG_GRY="\e[100m"
export BG_BLK="\e[40m"
export BG_DEF="\e[49m"

export ANSIBLE_NOCOWS=1
export COPYFILE_DISABLE=1
export CTL_DNSMASQ='homebrew.mxcl.dnsmasq'
export EDITOR="vim"
export HISTCONTROL=ignoreboth:erasedups
export LS_COLORS='di=38;5;108:fi=00:*svn-commit.tmp=31:ln=38;5;116:ex=38;5;186'
export PATH_HOMEBREW="$(brew --prefix 2>/dev/null)"
export PROMPT_COMMAND='PS1X=$(p="${PWD#${HOME}}"; [ "${PWD}" != "${p}" ] && printf "~";IFS=/; for q in ${p:1}; do printf /${q:0:1}; done; printf "${q:1}")'
export BASE_PS1="${BLU}\u@\h${GRY}:${CYN}\${PS1X}${RESET}${RED}\$${RESET} "
export PS1="${GRY}\D{%T}> $BASE_PS1"
export TERM="xterm-256color"
export WORKON_HOME=/opt/virtualenv
export PROJECT_HOME="$WORKON_HOME"
export VIRTUALENVWRAPPER_HOOK_DIR=/opt/virtualenv
