#!/usr/bin/env bash

path_prepend() {
  for d in $@; do
    # [[ ":$PATH:" != *":${d}:"* ]] && PATH="${d}:${PATH}";
    PATH="$d:$(python -c "import os,sys; p=[d for d in os.environ['PATH'].split(os.pathsep) if d != '$d']; sys.stdout.write(os.pathsep.join(p))")"
  done

  export PATH
}
